### ISSUE TITLE
MW 1.28 failed

### ISSUE THREAD

**Issue by zoglun** [imbushuo/MmixCaptcha#1]
发生了一些问题
请稍等片刻后再试（点击此区域可以重试）。

REF A: PRECONNFAILURE

&

Undefined variable: output in <b>/extensions/ConfirmEdit/MmixCaptcha/HTMLMmixCaptchaWidgetField.php</b> on line <b>67</b><br />

**Comment by imbushuo** [comment]
Issue of undefined variable was addressed in 979dce7807d5da8698673a523fac07c6c7824bad.

"PRECONDITIONFAILURE" is related to CORS policy (`/etc/mmix/corsPolicy.json`, or just `corsPolicy.json` on Windows Server) on server side, it's easy to resolve on on-premise deployment (which is coming soon), for now I will allow all domains in the CORS policy.

**Comment by imbushuo** [comment]
CORS issue was addressed via a latest server deployment.
